### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by MatheusLPS85** [ParagonVirtuoso/reconhecimentoGestos#1]
erro na linha 27 camdetector porfavor mim ajuda tou precisando muito desse codigo porque vou apresentar na minha escola

**Comment by MatheusLPS85** [comment]
erro na linha 27 camdetector porfavor mim ajuda

**Comment by ParagonVirtuoso** [comment]
Explique mais sobre o erro.

**Comment by ParagonVirtuoso** [comment]
> erro na linha 27 camdetector porfavor mim ajuda tou precisando muito desse codigo porque vou apresentar na minha escola

criado documentação de como rodar o projeto e disponibilizado uma url para baixar os arquivos necessarios para executar o projeto.

**Comment by MatheusLPS85** [comment]
Você tinha como mim ajuda irmão tou precisando desse projeto

**Comment by ParagonVirtuoso** [comment]
> Você tinha como mim ajuda irmão tou precisando desse projeto 

Olha o arquivo readme.md do projeto.
Adicionei os passos de como rodar o projeto la, junto com o link do arquivo pra baixar.

**Comment by MatheusLPS85** [comment]
"Para executar o projeto, siga os passos abaixo: após baixar os arquivos do modelo de pose, coloque-os na pasta pose na raiz do projeto. ficando assim "pose/hand/pose_deploy.prototxt" e "pose/hand/pose_iter_102000.caffemodel" com os arquivos de modelo de pose na pasta pose."

Tem que cria uma pasta pose ?

**Comment by MatheusLPS85** [comment]
Ok
